export const state = {
    mounted: false,
    activeTab: "Discover",
    assetKind: "lora",
    selectedCategory: "",
    selectedCivitaiCategory: "",
    selectedBaseModel: "",
    selectedTag: "",
    taxonomyByKind: {},
    taxonomyLoading: false,
    query: "",
    sort: "Highest Rated",
    cursor: "",
    nextCursor: "",
    loadingSearch: false,
    autoLoadingMore: false,
    searchItems: [],
    selectedModel: null,
    selectedVersionId: "",
    selectedFileName: "",
    detailPreviewIndex: 0,
    pathOverrides: {},
    resolution: null,
    resolvingPath: false,
    libraryLoading: false,
    libraryFilter: "all",
    libraryItems: [],
    expandedLocalFolders: {},
    selectedAssetId: "",
    downloads: {},
    config: null,
    settingsSaving: false,
    apiTesting: false,
    error: "",
    toast: "",
    scroll: {
        discoverResults: 0,
        libraryResults: 0,
    },
};
